title: Shi Heng’s Blog

author: Shi Heng

email: lucienlorca@foxmail.com

url: https://shi-heng.com

description: > # this means to ignore newlines until "baseurl:"
  Shi Heng is a digital designer, writer and poet based in China.

baseurl: ""

lang: en # site language (en/ja/zh-Hans/zh-Hant)

color_scheme: github # this specifies color scheme for syntax highlighting

weibo_username: lucientes

douban_username: Zeitkritik

# Build settings
markdown: kramdown

remote_theme: kamikat/jekyll-theme-kagami

exclude:
- Gemfile
  - Gemfile.lock

