title: Shi Heng’s Blog

author: Shi Heng

email: lucienlorca@foxmail.com

url: https://shi-heng.com

description: > # this means to ignore newlines until "baseurl:"
  時衡，设计师，写作者，1993 年生于江苏无锡。这里是他的博客，用以盛放他涌动的灵感。“No poem is intended for the reader, no picture for the beholder, no symphony for the listener.” 写作亦如本雅明的这段论述，自娱，而后娱人。

baseurl: ""

lang: zh-Hans # site language (en/ja/zh-Hans/zh-Hant)

color_scheme: github # this specifies color scheme for syntax highlighting

douban_username: Zeitkritik

# Build settings
markdown: kramdown

remote_theme: kamikat/jekyll-theme-kagami

exclude:
- Gemfile
  - Gemfile.lock

