title: Shi Heng’s Blog

author: Shi Heng

email: lucienlorca@foxmail.com

url: https://shi-heng.com

description: > # this means to ignore newlines until "baseurl:"
  Shi Heng is a designer & writer based in Shanghai. 
  Here is his blog, where his inspiration flows. 
  “No poem is intended for the reader, no picture for the beholder, no symphony for the listener.” 
  Writing is like Walter Benjamin’s discourse, to entertain oneself and then to entertain others.

baseurl: ""

lang: zh-Hant # site language (en/ja/zh-Hans/zh-Hant)

color_scheme: github # this specifies color scheme for syntax highlighting

douban_username: Zeitkritik

# Build settings
markdown: kramdown

remote_theme: kamikat/jekyll-theme-kagami

exclude:
- Gemfile
  - Gemfile.lock

