title: Shi Heng's Blog

author: Shi Heng

email: hi@shihheng.com

url: https://shihheng.com

description: > # this means to ignore newlines until "baseurl:"
  Shi Heng is a writer and designer based in Wuxi, China.

baseurl: ""

lang: en # site language (en/ja/zh-Hans/zh-Hant)

color_scheme: github # this specifies color scheme for syntax highlighting

weibo_username: lucientes

zhihu_username: lorcha

douban_username: LucienLorca

# Build settings
markdown: kramdown

theme: jekyll-theme-kagami

exclude:
- Gemfile
  - Gemfile.lock

