title: Shi Heng's Blog

author: Shi Heng

email: hi@zihaolu.com

name: Shi Heng's Blog

description: > # this means to ignore newlines until "baseurl:"
  Shi Heng is a writer & designer based in Wuxi, China.

baseurl: ""

url: "https://zihaolu.io"

lang: en # site language (en/ja/zh-Hans/zh-Hant)

color_scheme: github # this specifies color scheme for syntax highlighting

weibo_username: lucientes

zhihu_username: lorcha

douban_username: LucienLorca

# Build settings
markdown: kramdown

theme: jekyll-theme-kagami

exclude:
- Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 8
paginate_path: /page/:num

